packages:
  - 'packages/*'

catalog:
  tsx:  ^4.20.6
  turbo: ^2.6.1
  typescript: ^5.9.3

catalogs:
  eslint:
    "@eslint/eslintrc": 3.3.1
    "@stylistic/eslint-plugin": ^5.5.0
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-react: 7.37.5
    globals: ^16.5.0
    typescript-eslint: ^8.46.4
    eslint: ^9.39.1

  minimist:
    "@types/minimist": ^1.2.5
    minimist: ^1.2.8

  node:
    "@types/node": ^24.10.1
